[build]
environment = { PYTHON_VERSION = "3.8", NODE_VERSION = "16", NPM_VERSION = "9.1.3" }

command = "npm run netlify"
publish = "examples"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"