[build]
environment = { PYTHON_VERSION = "3.8", NODE_VERSION = "20.18.1", NPM_VERSION = "10.8.2"}

command = "npm run netlify"
publish = "examples"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"